# Alice's test Config

usedurablestore = true

msgport = 3005
rpcport = 4005

pk = "2d999770f7b5d49b694080f987b82bbc9fc9ac2b4dcc10b0f8aba7d700f69c6d"
chainpk = "59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"

chainurl = "ws://127.0.0.1:8545"
chainauthtoken = ""

# Connect to Ivan
bootpeers = "/ip4/127.0.0.1/tcp/3008/p2p/16Uiu2HAm1hgN2MkrhGen8JPrBBYyXACbZtfqJmraN53XiHYCeoFi"
usemdns = false
