usedurablestore = true
durablestorefolder = "/app/data"

msgport = 3005
rpcport = 4005
guiport = 5005

# State Channel Public Address: 0xA72DBe31224b824c438606196bE5857C6bE4cB32
pk = ""

# Chain Public Address: 0xB62da17fab129AD3DF8858B7B1a834e570b8eead
chainpk = ""

naaddress = "0xe32d4B5C5a80660710f6a2aD3cB1c11664138F34"
vpaaddress = "0x4D1a804e1cE383D75032C52878553212992C98D7"
caaddress = "0x0C9D79725afc344A388045235CD0B23eA4f0E838"

# RPC provider docs: https://lotus.filecoin.io/lotus/developers/glif-nodes/#testnet-endpoint
chainurl = "wss://wss.calibration.node.glif.io/apigw/lotus/rpc/v0"
chainstartblock = 909569
chainauthtoken = ""

bootpeers = "/ip4/67.207.88.72/tcp/3005/p2p/16Uiu2HAmDQj9XnHPD1d4GzS1K3DhmM5Z1cSGLfVTwVcNVdEsAN3Q"
