name: Go

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.18.0"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.45.2

      - name: make bin folder
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: install GoVector
        run: GOPATH=$($GITHUB_WORKSPACE/bin) go install github.com/DistributedClocks/GoVector@latest

      - name: Build
        run: go build -v ./...

      - name: Test
        timeout-minutes: 1
        run: go test -v ./... -count=2 -shuffle=on

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: integration-test-logs
          path: ./**/*.log

      - name: Tidy
        run: go mod tidy

      - name: check git tree is clean
        # This will fail the job if any previous step (re)generated a file
        # that doesn't match what you checked in (or forgot to check in)
        run: git diff --exit-code
