name: Node

on:
  push:
    branches: [main]
  pull_request:
    paths: ["nitro-protocol/**", ".github/workflows/node.yml"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nitro-protocol
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Compile contracts
        run: npx hardhat compile
      - name: Run eslint (including prettier)
        run: npm run lint:check
      - name: Run gas benchmarks
        run: npm run benchmark:diff
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./**/*.log
      - name: Run tests
        run: npm test
      - name: Notify slack fail
        if: ${{ failure() && github.ref == 'refs/heads/main'}}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C03G4AUGA7M
          status: FAILED
          color: danger
